### ISSUE TITLE
Using CARSKit with implicit feedback

### ISSUE THREAD

**Issue by MatthiasKirsch** [irecsys/CARSKit#10]
Hi :) 

I am using CARSKit with BPR for top-N recommendation. My dataset is purchase data so I have only implicit feedback (more precisely I just know what the user bought). I added some cool stuff like weather information and demographic stuff about the cities of the stores etc. 

When using CARSKit I only applied BPR with Pre-filtering techniques (User-, item-, uisplitting) so far because of the implicit feedback. 

1. Is there another approach I should try out? For example CSLIM?
2. Is it possible to use a hybrid filtering approach like DCR/DCW/BPSO in combination with BPR?

Many thanks in advance!! :)

**Comment by irecsys** [comment]
Sounds good.

But unfortunately, we do not know which algorithm will perform the best by given a data. You have to try multiple algorithms to find the best one.

Based on my experience, if you'd like to see a good results on top-N recommendations, you can try SLIM based approach or CAMF_ICS, CAMF_MCS, CAMF_LCS. For SLIM-based approach, you need to carefully to find the optimal parameters. CAMF_ICS works good in most cases, CAMF_MCS can work even better if you carefully tune up the parameters.

In terms of the hybrid filtering approach like DCR/DCW/BPSO, you cannot try BPR, they were built based on the user-based collaborative filtering.

**Comment by MatthiasKirsch** [comment]
Thank you very much for your response! 

My problem is that I have implicit feedback so my rating matrix has only values 0 and 1. 
Because of this I cannot use algorithms like CAMF and some other context-aware algorithms, I think.

I read about that CSLIM might be able to handle this type of implicit feedback. Do you have experience with such cases? 

Many thanks in advance :)

**Comment by irecsys** [comment]
I do not think so. SLIM is another item-based collaborative filtering,
actually.
