### ISSUE TITLE
NA values

### ISSUE THREAD

**Issue by zainab2014** [irecsys/CARSKit#17]
Hi,
1)Please, I wanted to know, is it MANDATORY to have some NA values in the context fields if I am planning to use similarity CAMF?
2) If the answer in 1 is yes, how should I assign them in my dataset, just randomly change some context condition to be NA?
3)Kindly can you confirm if the format below is correct for the input file as I get 1 all the time in REC10 when I choose CAMF models?

userid,itemid,rating,p1,p2,p3,p4
1,1,3,NA,NA,NA,NA
1,1,3,NA,NA,NA,NA
1,1,3,NA,NA,NA,NA
1,1,3,NA,NA,NA,NA
1,1,4,X-Large,X-Small,Nominal,Small
1,1,3,NA,NA,NA,NA
1,1,2,X-Large,X-Large,Numeric,X-Large
1,1,3,NA,NA,NA,NA
1,1,3,NA,NA,NA,NA
1,1,3,NA,NA,NA,NA
1,1,2,NA,NA,NA,NA
1,1,2,X-Large,X-Large,Numeric,X-Large
1,1,2,X-Large,X-Large,Numeric,X-Large
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,4,X-Large,X-Small,Numeric,X-Small
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,5,NA,NA,NA,NA
1,1,4,Large,X-Small,Numeric,X-Small
1,1,4,X-Large,X-Small,Numeric,X-Small
1,1,4,X-Large,X-Small,Numeric,X-Small
1,1,4,Large,X-Small,Numeric,X-Small
1,1,5,NA,NA,NA,NA
Thank you.

**Comment by irecsys** [comment]
The option of "NA" is only applied when you have missing values in the data. CARSKit will automatically add this context condition in data transformations. A rating with all "NA" conditions is referred to a rating without considering contexts.

The input format could be binary, compact or loose format. Please refer to the CARSKit guide.
Your data format looks good to me.

**Comment by zainab2014** [comment]
Thank you so much for your reply.

**Can I use the deviation based for predicting?**

I just tried them with the new release and they worked, just wanted to confirm this issue.
I am looking for your reply with appreciation.
