### ISSUE TITLE
Using many different models

### ISSUE THREAD

**Issue by zainab2014** [irecsys/CARSKit#18]
Is it possible to do some changes to the config file in order to be able to call different models one time, for example, if I want the results from MF and BiasedMF is there a method other than run the tool many times?
Thank you so much.

**Comment by irecsys** [comment]
Please refer to the CARSKit guide, https://arxiv.org/abs/1511.03780
It has been introduced in the guide.
Also, you need to tune up paramters for each model. We do not suggest to run several models at the same time
