### ISSUE TITLE
CARS - dependent-dev models

### ISSUE THREAD

**Issue by zainab2014** [irecsys/CARSKit#19]
Hi Dr.,
What I understand from the tool documents the CARS - dependent-sim models are used for Ranking only.

My Question is: 
**Can w use the deviation based(CARS - dependent-dev models) for predicting?**

I just tried them with the new release and they worked, just wanted to confirm this issue.
I am looking for your reply with appreciation.

**Comment by irecsys** [comment]
I suggest you to understand each algorithm before the usage. I do not think you understand most of the CARS algorithms.
