### ISSUE TITLE
Setting up seed for algorithms with initialization

### ISSUE THREAD

**Issue by haonanzhang-vv** [irecsys/CARSKit#20]
Hi Prof. Zheng,

I saw the CV can specify the random seed, but I think it is for data partition?

I want to reproduce the result (MAP, NDCG), and I use CAMF_CU, whose fitting requires initialisation and gradient descent. I am wondering whether there is a way that I can fix the initialization for the gradient descent? Fix the initial value?

Also, I am wondering how do you use command line code to compile the java scripts into jar file? Would you mind sharing that command in this space. 

Thank you for your consideration.

**Comment by irecsys** [comment]
Hello, thanks for your interests in CARSKit. 

CARSKit was built upon LibRec v1.4. The library will create random initializations in the iterative learning  methods, such as algorithms based on matrix factorization. If you would like to fix the initializations, you need to download a copy of the source codes, and change the coding.

In terms of the jar file, I used the function in the IDE IntelliJ IDEA, https://www.jetbrains.com/idea/

**Comment by haonanzhang-vv** [comment]
Dear Prof. Zheng,

Thank you for your quick response. 

Yes, I am using Intelli J to compile the file. I am wondering whether we could have a quick zoom chat as I cannot successfully compile the Jar file. I really appreciate your work and hope to have a chat with you if possible.

Thank you for your consideration!

**Comment by irecsys** [comment]
Problems solved offline. Issue closed.
